# Generated by Django 3.0.1 on 2022-11-10 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=200)),
                ('homeTeamScore', models.IntegerField(default=0)),
                ('awayTeamScore', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('awayTeam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='awayTeam', to='championnat.Team')),
                ('homeTeam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='homeTeam', to='championnat.Team')),
            ],
        ),
    ]
