# Generated by Django 3.0.1 on 2022-11-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championnat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='endTime',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='startTime',
            new_name='startDate',
        ),
    ]
