# Generated by Django 4.1.1 on 2022-11-14 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championnat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='awayTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='awayGames', to='championnat.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='homeTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='homeGames', to='championnat.team'),
        ),
        migrations.CreateModel(
            name='GameComment',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('but', 'but'), ('carton jaune', 'carton jaune'), ('carton rouge', 'carton rouge')], max_length=15)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='championnat.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='championnat.player')),
            ],
        ),
    ]
