# Generated by Django 3.0.1 on 2022-11-11 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championnat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='games', to='championnat.League'),
        ),
    ]
