# Generated by Django 4.1.1 on 2022-11-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championnat', '0002_alter_game_awayteam_alter_game_hometeam_gamecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='buts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='cartes_jaunes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='cartes_rouges',
            field=models.IntegerField(default=0),
        ),
    ]
