# Generated by Django 4.1.1 on 2022-11-14 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championnat', '0003_player_buts_player_cartes_jaunes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='cartes_jaunes',
            new_name='cartons_jaunes',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='cartes_rouges',
            new_name='cartons_rouges',
        ),
        migrations.AlterField(
            model_name='game',
            name='awayTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayGames', to='championnat.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='homeTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeGames', to='championnat.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='championnat.league'),
        ),
        migrations.AlterField(
            model_name='gamecomment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='championnat.game'),
        ),
        migrations.AlterField(
            model_name='gamecomment',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='championnat.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='championnat.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='championnat.league'),
        ),
    ]
