# Generated by Django 4.1.1 on 2022-11-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championnat', '0006_game_dayinleague_game_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='startDate',
        ),
        migrations.AddField(
            model_name='game',
            name='firstHalfEndDate',
            field=models.DateTimeField(default='2022-11-17T00:00:00.000Z'),
        ),
        migrations.AddField(
            model_name='game',
            name='firstHalfFinished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='firstHalfStartDate',
            field=models.DateTimeField(default='2022-11-17T00:00:00.000Z'),
        ),
        migrations.AddField(
            model_name='game',
            name='secondHalfEndDate',
            field=models.DateTimeField(default='2022-11-17T00:00:00.000Z'),
        ),
        migrations.AddField(
            model_name='game',
            name='secondHalfStartDate',
            field=models.DateTimeField(default='2022-11-17T00:00:00.000Z'),
        ),
    ]
