# Generated by Django 4.1.1 on 2022-11-18 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championnat', '0007_remove_game_startdate_game_firsthalfenddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='firstHalfEndDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 1, 11, 37, 663373)),
        ),
        migrations.AlterField(
            model_name='game',
            name='firstHalfStartDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 1, 11, 37, 663355)),
        ),
        migrations.AlterField(
            model_name='game',
            name='secondHalfEndDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 1, 11, 37, 663393)),
        ),
        migrations.AlterField(
            model_name='game',
            name='secondHalfStartDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 1, 11, 37, 663385)),
        ),
    ]
