# Generated by Django 4.1.1 on 2022-11-18 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championnat', '0008_alter_game_firsthalfenddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='secondHalfStarted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='firstHalfEndDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 1, 33, 55, 507949)),
        ),
        migrations.AlterField(
            model_name='game',
            name='firstHalfStartDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 1, 33, 55, 507933)),
        ),
        migrations.AlterField(
            model_name='game',
            name='secondHalfEndDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 1, 33, 55, 507966)),
        ),
        migrations.AlterField(
            model_name='game',
            name='secondHalfStartDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 1, 33, 55, 507957)),
        ),
    ]
